[package]
name = "modern-unimi-thesis"
version = "1.0.0"
entrypoint = "src/lib.typ"
authors = ["Vittorio Robecchi <https://www.github.com/victuarvi"]
license = "MIT-0"
description = "Unofficial thesis template for Università Statale degli Studi di Milano."
repository = "https://github.com/VictuarVi/Template-Tesi-UniMi"
keywords = ["thesis", "unimi", "università statale degli studi di milano"]
categories = ["thesis", "paper"]
disciplines = ["computer-science", "mathematics", "physics"]
compiler = "0.13.0"
exclude = [ "src/fonts" ]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
